# Generated by Django 3.1.2 on 2020-10-21 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=50, null=True)),
                ('warranty', models.CharField(max_length=200, null=True)),
                ('details', models.CharField(max_length=1000, null=True)),
                ('manifactDetls', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='showDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.showdetails'),
        ),
    ]
